### ISSUE TITLE
issue about Single image view synthesis for ShapeNet

### ISSUE THREAD

**Issue by LiXinghui-666** [tancik/learnit#10]
I would like to ask about your experimental part in Single image view synthesis for ShapeNet, you are using only one image in the meta-learning stage under the setting of SV Meta, which means that only one image is used for the whole training process to generate the class(car or chair) 360 degree reconstruction effect for all instances?

**Comment by tancik** [comment]
The SV meta setup trains on a dataset of objects (ie chairs) but only observes a single viewpoint for each object.
