### ISSUE TITLE
DATA_PATH in the shapenet.ipynb

### ISSUE THREAD

**Issue by emjay73** [tancik/learnit#12]
In the file titled 'shapenet.ipynb', where can I find the dataset that corresponds to the following path?
DATA_PATH = '/projects/learnit/Experiments/03001627' # Update
Thank you.

**Comment by emjay73** [comment]
I found it from cars.zip. Thank you

**Comment by bkoyuncu** [comment]
@emjay73 How did you download cars.zip?
