### ISSUE TITLE
How to split the dataset for phototoursim experiments?

### ISSUE THREAD

**Issue by sanowar-raihan** [tancik/learnit#3]
Hi, thanks for the great work! It is really cool to see how simple meta-learning algorithms can be useful for phototourism.

But I couldn't find any splits file mentioning which images to use for test and validation. How do you make the split for different landmark scenes?

**Comment by tancik** [comment]
The splits are done in the code - https://github.com/tancik/learnit/blob/main/Experiments/phototourism.ipynb
Essentially the first 20 images are test, the next 5 are validation, and the remainder are training.

**Comment by sanowar-raihan** [comment]
Got it, thanks!
