### ISSUE TITLE
final dists value: small vs large

### ISSUE THREAD

**Issue by sanowar-raihan** [tancik/learnit#4]
The `phototourism` experiment sets the final `dists` vaule to a very big number, like `1e10`:
`dists = np.concatenate([z_vals[..., 1:] - z_vals[..., :-1], np.broadcast_to([1e10], z_vals[...,:1].shape)], -1)`

On the other hand, the `shapenet` experiment uses a small number `1e-3` for the final `dists`:
`dists = np.concatenate([z_vals[..., 1:] - z_vals[..., :-1], np.broadcast_to([1e-3], z_vals[...,:1].shape)], -1) `

What does it mean to have a very small or large value for the final `dists`? As I understand, the scene contents are expected to be bounded between `near` and `far` plane. So does it matter what value I set for the final `dists`?

Sorry if this is a silly question. I couldn't find an answer after searching through other nerf repos.

**Comment by tancik** [comment]
This essentially sets the last bin for photo tourism to be infinitely far. This helps catch any scene content that is very far away such as the sky (which is not accounted for by the near/far bounds). This "hack" isn't needed when the bounds are correct in the shapenet case.

**Comment by sanowar-raihan** [comment]
Thanks! That was a clear explanation.
