### ISSUE TITLE
cannot import name 'pytree' from 'jaxlib'

### ISSUE THREAD

**Issue by danperazzo** [tancik/learnit#6]
Hello everyone, thank you for sharing this experiments for this wonderfull project! Which version of Jax did you use? and could you share the requirements? I am trying to replicate the experiments and, when I download the Jax and jaxlibrary as mentioned on the readme I get this error :/

**Comment by tancik** [comment]
That is very odd. Are you certain that you are using jax 0.1.67 and jaxlib 0.1.55? Try printing jax.__version__ and jaxlib.__version__

**Comment by danperazzo** [comment]
I have mada a little [script](https://colab.research.google.com/drive/1NQlgWt97_riosNL4gTccOgBSXx77m3eo?usp=sharing) in colab with the error I get when importing jax. Am I doing something wrong?

**Comment by tancik** [comment]
Thanks for the colab. Try using jax==0.2.1
If this works for you, I will update the readme.

**Comment by danperazzo** [comment]
Now it works. However, I had also to use jaxlib==0.1.55
I think if you change this, it will always work :)

**Comment by tancik** [comment]
Can you post the error message.

**Comment by danperazzo** [comment]
`AttributeError                            Traceback (most recent call last)
<ipython-input-15-9a5e7d190a7f> in <module>()
     13 
     14 opt = optix.adam(lr)
---> 15 opt_state = opt.init(params)
     16 
     17 test_inner_steps = 64

AttributeError: 'Optimizer' object has no attribute 'init'`

**Comment by tancik** [comment]
It looks like you changed the optix import in the colab. It should be `from jax.experimental import optix`

Also if you want to use the GPU you need to modify the jaxlib install ->
`pip install -q jaxlib==0.1.55+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html`

Note that this command is for cuda 11.0 which is what colab is currently using. You can find the current cuda version by running `nvcc -V`

**Comment by danperazzo** [comment]
It works now, thank you very much!
